//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESeller_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_farmer
    {
        public int far_id { get; set; }
        [Required(ErrorMessage = "*")]
        public string far_name { get; set; }
        [Required(ErrorMessage = "*")]
        public string far_email { get; set; }
        [Required(ErrorMessage = "*")]
        public string far_password { get; set; }
        [Required(ErrorMessage = "*")]
        public string far_contact { get; set; }
    }
}
