//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESeller_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tbl_product
    {
        public int pro_id { get; set; }
        [Required(ErrorMessage = "*")]
        [DisplayName("Name")]
        public string pro_name { get; set; }
        [Required(ErrorMessage = "*")]
        [DisplayName("Image")]
        public string pro_image { get; set; }
        [Required(ErrorMessage = "*")]
        [DisplayName("Price")]
        public string pro_price { get; set; }
        [Required(ErrorMessage = "*")]
        [DisplayName("Farmer Address")]
        public string pro_farmer_adderess { get; set; }
        [Required(ErrorMessage = "*")]
        [DisplayName("Farmer Contact")]
        public string pro_farmer_contact { get; set; }
        [Required(ErrorMessage = "*")]
        [DisplayName("Description")]
        public string pro_des { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
